# Generated by Django 4.2 on 2025-01-20 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('encrypted_filename', models.CharField(default=files.models.default_encrypted_filename, max_length=255, unique=True)),
                ('original_file_size', models.BigIntegerField(default=0)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('encryption_iv', models.BinaryField(default=files.models.default_iv)),
                ('encrypted_file_key', models.BinaryField(default=files.models.default_encrypted_key)),
                ('server_side_iv', models.BinaryField(default=files.models.default_iv)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('encrypted_content', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
                'ordering': ['-upload_timestamp'],
            },
        ),
    ]
