# Generated by Django 5.0 on 2024-12-30 08:34

from django.db import migrations, models
import secrets

def generate_iv():
    return secrets.token_bytes(16)

def generate_key():
    return secrets.token_bytes(32)

class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(default=generate_key),
        ),
        migrations.AlterField(
            model_name='file',
            name='encryption_iv',
            field=models.BinaryField(default=generate_iv),
        ),
    ]
