version: '3.8'

services:
  backend:
    build: 
      context: ./secure-file-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./secure-file-backend:/app
      - media_files:/app/media
    environment:
      - DEBUG=0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  media_files: 