services:
  - type: web
    name: secure-file-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn secure_file.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false  # Will be set manually in Render dashboard
      - key: SECRET_KEY
        sync: false  # Will be set manually in Render dashboard
    autoDeploy: true

  - type: web
    name: secure-file-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false  # Will be set manually in Render dashboard
    autoDeploy: true 