# Generated by Django 5.0 on 2025-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enable_mfa_for_existing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
