# Generated by Django 4.2 on 2025-01-21 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharepermission',
            options={'ordering': ['-created_at'], 'verbose_name': 'share permission', 'verbose_name_plural': 'share permissions'},
        ),
        migrations.RemoveIndex(
            model_name='sharepermission',
            name='shares_shar_share_l_e2ec02_idx',
        ),
        migrations.RemoveIndex(
            model_name='sharepermission',
            name='shares_shar_file_id_37030c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='sharepermission',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sharepermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this share link expires', null=True),
        ),
        migrations.AlterField(
            model_name='sharepermission',
            name='is_download_enabled',
            field=models.BooleanField(default=False, help_text='Whether downloads are currently enabled'),
        ),
        migrations.AlterField(
            model_name='sharepermission',
            name='share_link_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
